modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "pumpkinpal"
version = "${version}"
displayName = "Pumpkin Pal"
authors = "Superkat32"
description = '''
Made for SpookyJam 2023!
'''
logoFile = "icon"

[[dependencies.pumpkinpal]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pumpkinpal]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pumpkinpal]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pumpkinpal]]
modId="geckolib"
mandatory=true
versionRange="[4.0.0,)"
ordering="NONE"
side="BOTH"